apiVersion: v1
kind: Service
metadata:
  name: grpc_test_client
  namespace: grpc_test
  labels:
    app: grpc_test_client
spec:
  selector:
    app: grpc_test_client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc_test_client
  namespace: grpc_test
  labels:
    app: grpc_test_client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc_test_client
  template:
    metadata:
      labels:
        app: grpc_test_client
    spec:
      containers:
      - name: grpc_test_client
        image: lucasgpulcinelli/grpc_test_client:GRPC_TEST_VERSION

