apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: grpc
  labels:
    app: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
    - port: 50501
      targetPort: 50501
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: grpc
  labels:
    app: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: lucasegp/grpc-server:latest
        ports:
        - containerPort: 50501
